/*
 * System rezerwacji miejsc na eventy
 *
 * Niniejsza dokumentacja stanowi opis REST API implemtowanego przez serwer centralny. Endpointy 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: XXX@pw.edu.pl
 * Generated by: https://openapi-generator.tech
 */

using dionizos_backend_app.Models;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using dionizos_backend_app;
using dionizos_backend_app.Extensions;
using Microsoft.EntityFrameworkCore;
using Org.OpenAPITools.Models;

namespace Org.OpenAPITools.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class CategoriesApiController : ControllerBase
    {
        DionizosDataContext _dionizosDataContext;
        IConfigurationRoot _config;
        IHelper _helper;
        public CategoriesApiController(DionizosDataContext dionizosDataContext, IConfigurationRoot config, IHelper helper)
        {
            _dionizosDataContext = dionizosDataContext;
            _config = config;
            _helper = helper;
        }

        /// <summary>
        /// Create new category
        /// </summary>
        /// <param name="sessionToken">session Token</param>
        /// <param name="categoryName">name of category</param>
        /// <response code="201">created</response>
        /// <response code="400">category already exist</response>
        [HttpPost]
        [Route("/categories")]
        public virtual async Task<IActionResult> AddCategories([FromHeader] [Required()] string sessionToken,
            [FromHeader][Required()]string categoryName)
        {
            var organizer = _helper.Validate(sessionToken);
            if (organizer is null) return StatusCode(403);
            if (categoryName.Length < 2 || categoryName.Length > 250) return StatusCode(400);


            if (!_dionizosDataContext.Categories.Any( x => x.Name == categoryName))
            {
                Category cat = new Category { Name = categoryName };
                await _dionizosDataContext.Categories.AddAsync(cat);
                await _dionizosDataContext.SaveChangesAsync();
                return StatusCode(201, cat.AsDto());
            }
            return StatusCode(400);
        }

        /// <summary>
        /// Return list of all categories
        /// </summary>
        /// <response code="200">successful operation</response>
        [HttpGet]
        [Route("/categories")]
        public virtual async Task<IActionResult> GetCategories()
        {
            List<CategoryDTO> categories = await _dionizosDataContext.Categories.Select(x => x.AsDto())
                                                                                .ToListAsync();
            return new ObjectResult(categories);
        }
    }
}
