/*
 * System rezerwacji miejsc na eventy
 *
 * Niniejsza dokumentacja stanowi opis REST API implemtowanego przez serwer centralny. Endpointy 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: XXX@pw.edu.pl
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using dionizos_backend_app;
using dionizos_backend_app.Extensions;
using dionizos_backend_app.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Org.OpenAPITools.Models;

namespace Org.OpenAPITools.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class EventApiController : ControllerBase
    {
        DionizosDataContext _dionizosDataContext;
        IHelper _helper;
        public EventApiController(DionizosDataContext dionizosDataContext, IHelper helper)
        {
            _dionizosDataContext = dionizosDataContext;
            _helper = helper;
        }
        /// <summary>
        /// Add new event
        /// </summary>
        /// <param name="sessionToken">session Token</param>
        /// <param name="title">title of EventDTO</param>
        /// <param name="name">title of EventDTO</param>
        /// <param name="freePlace">No of free places</param>
        /// <param name="startTime">Unix time stamp of begin of event</param>
        /// <param name="endTime">Unix time stamp of end of event</param>
        /// <param name="latitude">Latitude of event</param>
        /// <param name="longitude">Longitude of event</param>
        /// <param name="categories">Unix time stamp of end of event</param>
        /// <param name="placeSchema">seralized place schema</param>
        /// <response code="201">event created</response>
        /// <response code="400">event can not be created</response>
        [HttpPost]
        [Route("/events")]
        public virtual async Task<IActionResult > AddEvent([FromHeader][Required()] string sessionToken, [FromQuery][Required()] string title, [FromQuery][Required()] string name, [FromQuery][Required()] int? freePlace, [FromQuery][Required()] int? startTime, [FromQuery][Required()] int? endTime, [FromQuery][Required()] string latitude, [FromQuery][Required()] string longitude, [FromQuery][Required()] List<int?> categories, [FromQuery] string? placeSchema)
        {
            var organizer = _helper.Validate(sessionToken);
            if (organizer is null) return StatusCode(400);
            if (freePlace is null || startTime is null || endTime is null)
            {
                return StatusCode(400);
            }
            if (title.Length == 0 || title.Length > 250 || latitude.Length == 0 || latitude.Length > 20 ||
                longitude.Length == 0 || longitude.Length > 20) return StatusCode(400);
            int exisitng_categories_cnt =  _dionizosDataContext.Categories.Where(c => categories.Contains(c.Id)).Count();
            if (exisitng_categories_cnt != categories.Count) return StatusCode(400);
            if (freePlace < 0) return StatusCode(400);
            if (startTime < DateTimeOffset.UtcNow.ToUnixTimeSeconds()) return StatusCode(400);
            if (endTime < startTime) return StatusCode(400);
            if (endTime < DateTimeOffset.UtcNow.ToUnixTimeSeconds())return StatusCode(400);

            Event newEvent = new Event();
            newEvent.Title = title;
            newEvent.Latitude = latitude;
            newEvent.Longitude = longitude;
            newEvent.Owner = organizer.Id;
            newEvent.Name = name;
            newEvent.Starttime = DateTimeOffset.FromUnixTimeSeconds((long)startTime).DateTime;
            newEvent.Endtime = DateTimeOffset.FromUnixTimeSeconds((long)endTime).DateTime;
            newEvent.Placecapacity = (int)freePlace;
            newEvent.Status = (int)EventStatus.InFutureEnum;
            newEvent.Placeschema = placeSchema ?? "";

            await _dionizosDataContext.Events.AddAsync(newEvent);
            await _dionizosDataContext.SaveChangesAsync(); //aby uzyskac id eventu

            //add categories table
            foreach (var category in categories)
            {
                Eventincategory eventincategory = new Eventincategory();
                eventincategory.CategoriesId = category.Value;
                eventincategory.EventId = newEvent.Id;
                await _dionizosDataContext.Eventincategories.AddAsync(eventincategory);
            }

            await _dionizosDataContext.SaveChangesAsync();
            EventDTO dto = newEvent.AsDto();
            return StatusCode(200, dto);
        }

        /// <summary>
        /// Cancel event
        /// </summary>
        /// <param name="sessionToken">session Token</param>
        /// <param name="id">id of EventDTO</param>
        /// <response code="204">deleted</response>
        /// <response code="404">id not found</response>
        [HttpDelete]
        [Route("/events/{id}")]
        public virtual IActionResult CancelEvent([FromHeader][Required()]string sessionToken, [FromRoute (Name = "id")][Required]string id)
        {

            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Return list of all events in category
        /// </summary>
        /// <param name="categoryId">ID of category</param>
        /// <response code="200">successful operation</response>
        /// <response code="400">Invalid category ID supplied</response>
        [HttpGet]
        [Route("/events/getByCategory")]
        public virtual async Task<IActionResult> GetByCategory([FromQuery (Name = "categoryId")][Required()]long categoryId)
        {

            List<Eventincategory> eInC = await _dionizosDataContext.Eventincategories.Include(x => x.Event)
                                                                                     .Where(x => x.CategoriesId == categoryId)
                                                                                     .ToListAsync();
            return new ObjectResult(eInC.Select(x => x.Event.AsDto()).ToList());
        }

        /// <summary>
        /// Find event by ID
        /// </summary>
        /// <remarks>Returns a single event</remarks>
        /// <param name="id">ID of event to return</param>
        /// <response code="200">successful operation</response>
        /// <response code="400">Invalid ID supplied</response>
        /// <response code="404">EventDTO not found</response>
        [HttpGet]
        [Route("/events/{id}")]
        public virtual async Task<IActionResult> GetEventById([FromRoute (Name = "id")][Required]long id)
        {
            if (id < 1) return StatusCode(400);


            Event? e = await _dionizosDataContext.Events.FirstOrDefaultAsync(x => x.Id == id);
            if(e is null) StatusCode(404);
            return new ObjectResult(e.AsDto());
        }

        /// <summary>
        /// Return list of all events
        /// </summary>
        /// <response code="200">successful operation</response>
        [HttpGet]
        [Route("/events")]
        public virtual async Task<IActionResult> GetEvents()
        {
            List<EventDTO> events = _dionizosDataContext.Events.Select(x => x.AsDto()).ToList();
            return new ObjectResult(events);
        }

        /// <summary>
        /// Return list of events made by organizer, according to session
        /// </summary>
        /// <param name="sessionToken">session Token</param>
        /// <response code="200">successful operation</response>
        [HttpGet]
        [Route("/events/my")]
        public virtual async Task<IActionResult> GetMyEvents([FromHeader][Required()]string sessionToken)
        {

            var organizer = _helper.Validate(sessionToken);
            if (organizer is null) return StatusCode(400);

            List<EventDTO> events = await _dionizosDataContext.Events.Where(x => x.Owner == organizer.Id)
                                                                     .Select(x => x.AsDto()).ToListAsync();
            return new ObjectResult(events);
        }

        /// <summary>
        /// patch existing event
        /// </summary>
        /// <param name="sessionToken">session Token</param>
        /// <param name="id">id of EventDTO</param>
        /// <param name="_event">Update an existent user in the store</param>
        /// <response code="202">patched</response>
        /// <response code="404">id not found</response>
        [HttpPatch]
        [Route("/events/{id}")]
        [Consumes("application/json")]
        public virtual IActionResult PatchEvent([FromHeader][Required()]string sessionToken, [FromRoute (Name = "id")][Required]string id, [FromBody]EventDTO _event)
        {

            //TODO: Uncomment the next line to return response 202 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(202);
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            throw new NotImplementedException();
        }
    }
}
