/*
 * System rezerwacji miejsc na eventy
 *
 * Niniejsza dokumentacja stanowi opis REST API implemtowanego przez serwer centralny. Endpointy 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: XXX@pw.edu.pl
 * Generated by: https://openapi-generator.tech
 */

using dionizos_backend_app.Models;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using dionizos_backend_app;
using Category = Org.OpenAPITools.Models.Category;

namespace Org.OpenAPITools.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class CategoriesApiController : ControllerBase
    {
        DionizosDataContext _dionizosDataContext;
        IConfigurationRoot _config;
        IHelper _helper;
        public CategoriesApiController(DionizosDataContext dionizosDataContext, IConfigurationRoot config, IHelper helper)
        {
            _dionizosDataContext = dionizosDataContext;
            _config = config;
            _helper = helper;
        }

        /// <summary>
        /// Create new category
        /// </summary>
        /// <param name="sessionToken">session Token</param>
        /// <param name="categoryName">name of category</param>
        /// <response code="201">created</response>
        /// <response code="400">category already exist</response>
        [HttpPost]
        [Route("/categories")]
        public virtual IActionResult AddCategories([FromHeader] [Required()] string sessionToken,
            [FromQuery(Name = "categoryName")] [Required()] string categoryName)
        {
            var organizer = _helper.Validate(sessionToken);
            if (organizer is null) return StatusCode(400);
            if (categoryName.Length < 2 || categoryName.Length > 250) return StatusCode(400);

            if (!_dionizosDataContext.Categories.Any( x => x.Name == categoryName))
            {
                var cat = new dionizos_backend_app.Models.Category { Name = categoryName };
                _dionizosDataContext.Categories.Add(cat);
                _dionizosDataContext.SaveChanges();
                return StatusCode(201, cat);
            }
            return StatusCode(400);
        }

        /// <summary>
        /// Return list of all categories
        /// </summary>
        /// <response code="200">successful operation</response>
        [HttpGet]
        [Route("/categories")]
        public virtual IActionResult GetCategories()
        {
            return new ObjectResult(_dionizosDataContext.Categories.ToList());
        }
    }
}
