/*
 * System rezerwacji miejsc na eventy
 *
 * Niniejsza dokumentacja stanowi opis REST API implemtowanego przez serwer centralny. Endpointy 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: XXX@pw.edu.pl
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using dionizos_backend_app.Extensions;
using dionizos_backend_app.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Org.OpenAPITools.Models;

namespace Org.OpenAPITools.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class EventOrganizerApiController : ControllerBase
    {
        private readonly DionizosDataContext _context;

        public EventOrganizerApiController(DionizosDataContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Confirm orginizer account
        /// </summary>
        /// <param name="id">id of Organizer</param>
        /// <param name="code">code from email</param>
        /// <response code="201">account confirmed</response>
        /// <response code="400">code wrong</response>
        [HttpPost]
        [Route("/organizer/{id}")]
        public virtual async Task<IActionResult> Confirm([FromRoute (Name = "id")][Required]string id, [FromQuery (Name = "code")][Required()]string code)
        {
            int Id = int.Parse(id);
            // TODO: (kutakw) email verification
            Emailcode? entity = await _context.Emailcodes
                                            .FirstOrDefaultAsync(x => x.OrganizerId == Id);

            // verify id and code
            if(entity == null)
            {
                // wrong code, return bad request
                return StatusCode(400);
            }

            Organizer organizer = await _context.Organizers
                                             .Where(x => x.Id == Id)
                                             .FirstAsync();

            // update organizer status
            organizer.Status = (int)Organizer.StatusEnum.ConfirmedEnum;
            // save changes
            await _context.SaveChangesAsync();

            OrganizerDTO dto = organizer.AsDto(_context);
            return StatusCode(201, dto);
        }

        /// <summary>
        /// Confirm orginizer account
        /// </summary>
        /// <param name="sessionToken">session Token</param>
        /// <param name="id">id of Organizer</param>
        /// <response code="204">deleted</response>
        /// <response code="404">id not found</response>
        [HttpDelete]
        [Route("/organizer/{id}")]
        public virtual IActionResult DeleteOrganizer([FromHeader][Required()]string sessionToken, [FromRoute (Name = "id")][Required]string id)
        {

            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Logs organizer into the system
        /// </summary>
        /// <param name="email">The organizer email for login</param>
        /// <param name="password">the password</param>
        /// <response code="200">successful operation</response>
        /// <response code="400">Invalid email/password supplied</response>
        [HttpGet]
        [Route("/organizer/login")]
        public virtual async Task<IActionResult> LoginOrganizer([FromQuery (Name = "email")][Required()]string email, [FromQuery (Name = "password")][Required()]string password)
        {
            throw new NotImplementedException();

            // Check if organizer exists
            Organizer? organizer = await _context.Organizers
                                                 .FirstOrDefaultAsync(
                                                    x => x.Email == email 
                                                    && x.Password == password
                                                    && x.Status == (int)Organizer.StatusEnum.ConfirmedEnum);
            if(organizer == null)
            {
                // Invalid email/password
                return StatusCode(400);
            }

            // TODO: (kutakw) 2hrs is enough i guess
            DateTime time = DateTime.Now.AddHours(2.0);

            // Create new session with token
            Session session = new()
            {
                OrganizerId = organizer.Id,
                Time = time,
                // TODO: (kutakw) tbd
                Token = (email + time).Base64Encode(),
            };

            // update db
            await _context.Sessions.AddAsync(session);
            await _context.SaveChangesAsync();

            LoginOrganizer200ResponseDTO dto = session.AsDto();
            return StatusCode(200, dto);
        }

        /// <summary>
        /// Patch orginizer account
        /// </summary>
        /// <param name="sessionToken">session Token</param>
        /// <param name="id">id of Organizer</param>
        /// <param name="organizer">Update an existent user in the store</param>
        /// <response code="202">patched</response>
        /// <response code="404">id not found</response>
        [HttpPatch]
        [Route("/organizer/{id}")]
        [Consumes("application/json")]
        public virtual IActionResult PatchOrganizer([FromHeader][Required()]string sessionToken, [FromRoute (Name = "id")][Required]string id, [FromBody]OrganizerDTO organizer)
        {

            //TODO: Uncomment the next line to return response 202 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(202);
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Create orginizer account
        /// </summary>
        /// <param name="name">name of Organizer</param>
        /// <param name="email">email of Organizer</param>
        /// <param name="password">password of Organizer</param>
        /// <response code="201">successful operation</response>
        /// <response code="400">organizer already exist</response>
        [HttpPost]
        [Route("/organizer")]
        public virtual async Task<IActionResult> SignUp([FromQuery (Name = "name")][Required()]string name, [FromQuery (Name = "email")][Required()]string email, [FromQuery (Name = "password")][Required()]string password)
        {
            // Check if organizer with that name or email already exists
            Organizer? organizerInDb =
                await _context.Organizers
                              .FirstOrDefaultAsync(x => x.Name == name || x.Email == email);
            if (organizerInDb != null)
            {
                // return bad request and no body
                return StatusCode(400);
            }

            // FIXME: (kutakw) ?
            int organizerId = await _context.Organizers.AnyAsync()
                ? (await _context.Organizers
                           .Select(x => x.Id)
                           .MaxAsync()) + 1
                : 1;
            // Create new organizer
            Organizer organizer = new()
            {
                Id = organizerId,
                Email = email,
                Name = name,
                Password = password,
                Status = (int)Organizer.StatusEnum.PendingEnum,
            };
            // Add organizer to db
            await _context.Organizers.AddAsync(organizer);
            await _context.SaveChangesAsync();

            // FIXME: (kutakw) ?
            int emailcodeId = await _context.Emailcodes.AnyAsync()
                ? (await _context.Emailcodes
                           .Select(x => x.Id)
                           .MaxAsync()) + 1
                : 1;
            // Create Email Code
            Emailcode emailcode = new()
            {
                Id = emailcodeId,
                OrganizerId = organizer.Id,
                Time = DateTime.Now.AddDays(1.0),

                // FIXME: (kutakw) Probably we should change that :)
                Code = (organizer.Email.GetHashCode().ToString() 
                        + " "
                        + organizer.Name.ToString()).Base64Encode(),
            };

            // Add email code to db
            await _context.Emailcodes.AddAsync(emailcode);
            await _context.SaveChangesAsync();

            // TODO: (kutakw) send email with verification code

            OrganizerDTO dto = organizer.AsDto(_context);
            dto.Name = name;
            return StatusCode(201, dto);
        }
    }
}
