/*
 * System rezerwacji miejsc na eventy
 *
 * Niniejsza dokumentacja stanowi opis REST API implemtowanego przez serwer centralny. Endpointy 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: XXX@pw.edu.pl
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using dionizos_backend_app;
using dionizos_backend_app.Extensions;
using dionizos_backend_app.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Org.OpenAPITools.Models;

namespace Org.OpenAPITools.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class EventOrganizerApiController : ControllerBase
    {
        private readonly DionizosDataContext _context;
        private readonly Random _random = new();

        public EventOrganizerApiController(DionizosDataContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Confirm orginizer account
        /// </summary>
        /// <param name="id">id of Organizer</param>
        /// <param name="code">code from email</param>
        /// <response code="201">account confirmed</response>
        /// <response code="400">code wrong</response>
        [HttpPost]
        [Route("/organizer/{id}")]
        public virtual async Task<IActionResult> Confirm([FromRoute (Name = "id")][Required]string id, [FromQuery (Name = "code")][Required()]string code)
        {
            int Id = int.Parse(id);
            DateTime currTime = DateTime.Now;
            Emailcode? entity = await _context.Emailcodes
                                            .Include(x => x.Organizer)
                                            .FirstOrDefaultAsync(x =>
                                                x.OrganizerId == Id
                                                && x.Code == code
                                                && currTime < x.Time.AddDays(1.0));

            // verify id and code
            if (entity == null)
            {
                // wrong email/code, return bad request
                return StatusCode(400);
            }

            Organizer organizer = entity.Organizer;

            // update organizer status
            organizer.Status = (int)Organizer.StatusEnum.ConfirmedEnum;
            // save changes
            await _context.SaveChangesAsync();

            OrganizerDTO dto = organizer.AsDto();
            return StatusCode(201, dto);
        }

        /// <summary>
        /// Confirm orginizer account
        /// </summary>
        /// <param name="sessionToken">session Token</param>
        /// <param name="id">id of Organizer</param>
        /// <response code="204">deleted</response>
        /// <response code="404">id not found</response>
        [HttpDelete]
        [Route("/organizer/{id}")]
        public virtual async Task<IActionResult> DeleteOrganizer([FromHeader][Required()]string sessionToken, [FromRoute (Name = "id")][Required]string id)
        {
            int sessionLengthHours = 2;
            // Validate session
            if(!Helpers.isSessionValid(_context, sessionToken, TimeSpan.FromHours(sessionLengthHours)))
            {
                // invalid session
                return StatusCode(401);
            }

            int Id = int.Parse(id);
            Organizer? organizer = await _context.Organizers
                                           .Include(x => x.Events)
                                           .FirstOrDefaultAsync(x => x.Id == Id);

            if(organizer == null)
            {
                // No valid organizer with provided id
                return StatusCode(404);
            }

            // check if any planned or pending events exist
            if(organizer.Events.Any(x => 
                x.Status == (int)EventStatus.InFutureEnum
                || x.Status == (int)EventStatus.PendingEnum))
            {
                // FIXME: (kutakw) przydalby sie jakis status code
                return StatusCode(404);
            }

            // Hash all data of organizer
            organizer.Name = organizer.Name.GetHashCode().ToString();
            organizer.Email = organizer.Email.GetHashCode().ToString();
            organizer.Password = organizer.Password.GetHashCode().ToString();

            // Cancell all events
            foreach(Event ev in organizer.Events)
            {
                ev.Status = (int)EventStatus.CancelledEnum;
            }

            // save in db
            await _context.SaveChangesAsync();

            return StatusCode(204);
        }

        /// <summary>
        /// Logs organizer into the system
        /// </summary>
        /// <param name="email">The organizer email for login</param>
        /// <param name="password">the password</param>
        /// <response code="200">successful operation</response>
        /// <response code="400">Invalid email/password supplied</response>
        [HttpGet]
        [Route("/organizer/login")]
        public virtual async Task<IActionResult> LoginOrganizer([FromQuery (Name = "email")][Required()]string email, [FromQuery (Name = "password")][Required()]string password)
        {
            // Check if organizer exists
            Organizer? organizer = await _context.Organizers
                                                 .FirstOrDefaultAsync(
                                                    x => x.Email == email 
                                                    && x.Password == password
                                                    && x.Status == (int)Organizer.StatusEnum.ConfirmedEnum);
            if(organizer == null)
            {
                // Invalid email/password
                return StatusCode(400);
            }

            DateTime time = DateTime.Now.AddHours(2.0);

            // Create new session with token
            Session session = new()
            {
                OrganizerId = organizer.Id,
                Time = time,
                Token = Session.GetToken(email, time),
            };

            // update db
            await _context.Sessions.AddAsync(session);
            await _context.SaveChangesAsync();

            LoginOrganizer200ResponseDTO dto = session.AsDto();
            return StatusCode(200, dto);
        }

        /// <summary>
        /// Patch orginizer account
        /// </summary>
        /// <param name="sessionToken">session Token</param>
        /// <param name="id">id of Organizer</param>
        /// <param name="organizer">Update an existent user in the store</param>
        /// <response code="202">patched</response>
        /// <response code="404">id not found</response>
        [HttpPatch]
        [Route("/organizer/{id}")]
        [Consumes("application/json")]
        public virtual IActionResult PatchOrganizer([FromHeader][Required()]string sessionToken, [FromRoute (Name = "id")][Required]string id, [FromBody]OrganizerDTO organizer)
        {

            //TODO: Uncomment the next line to return response 202 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(202);
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Create orginizer account
        /// </summary>
        /// <param name="name">name of Organizer</param>
        /// <param name="email">email of Organizer</param>
        /// <param name="password">password of Organizer</param>
        /// <response code="201">successful operation</response>
        /// <response code="400">organizer already exist</response>
        [HttpPost]
        [Route("/organizer")]
        public virtual async Task<IActionResult> SignUp([FromQuery (Name = "name")][Required()]string name, [FromQuery (Name = "email")][Required()]string email, [FromQuery (Name = "password")][Required()]string password)
        {
            // Check if organizer with that name or email already exists
            Organizer? organizerInDb =
                await _context.Organizers
                              .FirstOrDefaultAsync(x => x.Name == name || x.Email == email);
            if (organizerInDb != null)
            {
                // return bad request and no body
                return StatusCode(400);
            }

            // Create new organizer
            Organizer organizer = new()
            {
                Email = email,
                Name = name,
                Password = password,
                Status = (int)Organizer.StatusEnum.PendingEnum,
            };
            // Add organizer to db
            await _context.Organizers.AddAsync(organizer);
            await _context.SaveChangesAsync();

            // Create Email Code
            Emailcode emailcode = new()
            {
                OrganizerId = organizer.Id,
                Time = DateTime.Now,
                Code = string.Join(
                    string.Empty,
                    Enumerable.Range(0, 6)
                              .Select(_ => _random.Next(0, 9).ToString())
                ),
            };

            // Add email code to db
            await _context.Emailcodes.AddAsync(emailcode);
            await _context.SaveChangesAsync();

            // TODO: (kutakw) send email with verification code

            OrganizerDTO dto = organizer.AsDto();
            return StatusCode(201, dto);
        }

        [HttpGet]
        [Route("/organizer/test")]
        public virtual async Task<IActionResult> Test()
        {
            const string email = "testOrg";
            const string username = "test";
            const string pass = "test";
            await SignUp(username, email, pass);

            Organizer organizer = await _context.Organizers
                                     .Include(x => x.Emailcodes)
                                     .Include(x => x.Events)
                                     .Include(x => x.Sessions)
                                     .FirstAsync(x => x.Email == email);

            await Confirm(organizer.Id.ToString(), organizer.Emailcodes.First().Code);
            await LoginOrganizer(email, pass);
            await _context.Entry(organizer).ReloadAsync();
            organizer.Events.Add(new Event
            {
                Title = "testEv1",
                Name = null,
                Starttime = DateTime.Now,
                Endtime = DateTime.Now,
                Latitude = "123",
                Longitude = "123",
                Categories = 0,
                Status = (int)EventStatus.InFutureEnum,
                Placecapacity = 120,
                Placeschema = null,
            });
            organizer.Events.Add(new Event
            {
                Title = "testEv2",
                Name = null,
                Starttime = DateTime.Now,
                Endtime = DateTime.Now.AddDays(1.0),
                Latitude = "2",
                Longitude = "2",
                Categories = 0,
                Status = (int)EventStatus.PendingEnum,
                Placecapacity = 160,
                Placeschema = null,
            });
            organizer.Events.Add(new Event
            {
                Title = "testEv3",
                Name = null,
                Starttime = DateTime.Now.AddDays(1.0),
                Endtime = DateTime.Now.AddDays(2.0),
                Latitude = "3",
                Longitude = "1",
                Categories = 0,
                Status = (int)EventStatus.DoneEnum,
                Placecapacity = 1,
                Placeschema = null,
            });
            await _context.SaveChangesAsync();
            OrganizerDTO dto = organizer.AsDto();
            await DeleteOrganizer(organizer.Emailcodes.Last().Code, organizer.Id.ToString());

            _context.Events.RemoveRange(organizer.Events);
            _context.Emailcodes.RemoveRange(organizer.Emailcodes);
            _context.Sessions.RemoveRange(organizer.Sessions);
            _context.Organizers.Remove(organizer);
            await _context.SaveChangesAsync();

            return StatusCode(200, dto);
        }
    }
}
