/*
 * System rezerwacji miejsc na eventy
 *
 * Niniejsza dokumentacja stanowi opis REST API implemtowanego przez serwer centralny. Endpointy 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: XXX@pw.edu.pl
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Org.OpenAPITools.Models;

namespace Org.OpenAPITools.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class EventApiController : ControllerBase
    { 
        /// <summary>
        /// Add new event
        /// </summary>
        /// <param name="sessionToken">session Token</param>
        /// <param name="title">title of Event</param>
        /// <param name="name">title of Event</param>
        /// <param name="freePlace">No of free places</param>
        /// <param name="startTime">Unix time stamp of begin of event</param>
        /// <param name="endTime">Unix time stamp of end of event</param>
        /// <param name="categories">Unix time stamp of end of event</param>
        /// <param name="placeSchema">seralized place schema</param>
        /// <response code="201">event created</response>
        /// <response code="400">event can not be created</response>
        [HttpPost]
        [Route("/events")]
        public virtual IActionResult AddEvent([FromHeader][Required()]string sessionToken, [FromQuery (Name = "title")][Required()]string title, [FromQuery (Name = "name")][Required()]string name, [FromQuery (Name = "freePlace")][Required()]int freePlace, [FromQuery (Name = "startTime")][Required()]int startTime, [FromQuery (Name = "endTime")][Required()]int endTime, [FromQuery (Name = "categories")][Required()]List<int> categories, [FromQuery (Name = "placeSchema")]string placeSchema)
        {

            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default(Event));
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);
            string exampleJson = null;
            exampleJson = "{\r\n  \"name\" : \"Long description of Event\",\r\n  \"freePlace\" : 2,\r\n  \"startTime\" : 1673034164,\r\n  \"id\" : 10,\r\n  \"endTime\" : 1683034164,\r\n  \"categories\" : [ {\r\n    \"name\" : \"Sport\",\r\n    \"id\" : 1\r\n  }, {\r\n    \"name\" : \"Sport\",\r\n    \"id\" : 1\r\n  } ],\r\n  \"title\" : \"Short description of Event\",\r\n  \"placeSchema\" : \"Seralized place schema\",\r\n  \"status\" : \"done\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<EventDTO>(exampleJson)
            : default(EventDTO);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Cancel event
        /// </summary>
        /// <param name="sessionToken">session Token</param>
        /// <param name="id">id of Event</param>
        /// <response code="204">deleted</response>
        /// <response code="404">id not found</response>
        [HttpDelete]
        [Route("/events/{id}")]
        public virtual IActionResult CancelEvent([FromHeader][Required()]string sessionToken, [FromRoute (Name = "id")][Required]string id)
        {

            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Return list of all events in category
        /// </summary>
        /// <param name="categoryId">ID of category</param>
        /// <response code="200">successful operation</response>
        /// <response code="400">Invalid category ID supplied</response>
        [HttpGet]
        [Route("/events/getByCategory")]
        public virtual IActionResult GetByCategory([FromQuery (Name = "categoryId")][Required()]long categoryId)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<Event>));
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);
            string exampleJson = null;
            exampleJson = "[ {\r\n  \"name\" : \"Long description of Event\",\r\n  \"freePlace\" : 2,\r\n  \"startTime\" : 1673034164,\r\n  \"id\" : 10,\r\n  \"endTime\" : 1683034164,\r\n  \"categories\" : [ {\r\n    \"name\" : \"Sport\",\r\n    \"id\" : 1\r\n  }, {\r\n    \"name\" : \"Sport\",\r\n    \"id\" : 1\r\n  } ],\r\n  \"title\" : \"Short description of Event\",\r\n  \"placeSchema\" : \"Seralized place schema\",\r\n  \"status\" : \"done\"\r\n}, {\r\n  \"name\" : \"Long description of Event\",\r\n  \"freePlace\" : 2,\r\n  \"startTime\" : 1673034164,\r\n  \"id\" : 10,\r\n  \"endTime\" : 1683034164,\r\n  \"categories\" : [ {\r\n    \"name\" : \"Sport\",\r\n    \"id\" : 1\r\n  }, {\r\n    \"name\" : \"Sport\",\r\n    \"id\" : 1\r\n  } ],\r\n  \"title\" : \"Short description of Event\",\r\n  \"placeSchema\" : \"Seralized place schema\",\r\n  \"status\" : \"done\"\r\n} ]";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<EventDTO>>(exampleJson)
            : default(List<EventDTO>);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Find event by ID
        /// </summary>
        /// <remarks>Returns a single event</remarks>
        /// <param name="id">ID of event to return</param>
        /// <response code="200">successful operation</response>
        /// <response code="400">Invalid ID supplied</response>
        /// <response code="404">Event not found</response>
        [HttpGet]
        [Route("/events/{id}")]
        public virtual IActionResult GetEventById([FromRoute (Name = "id")][Required]long id)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(Event));
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);
            string exampleJson = null;
            exampleJson = "{\r\n  \"name\" : \"Long description of Event\",\r\n  \"freePlace\" : 2,\r\n  \"startTime\" : 1673034164,\r\n  \"id\" : 10,\r\n  \"endTime\" : 1683034164,\r\n  \"categories\" : [ {\r\n    \"name\" : \"Sport\",\r\n    \"id\" : 1\r\n  }, {\r\n    \"name\" : \"Sport\",\r\n    \"id\" : 1\r\n  } ],\r\n  \"title\" : \"Short description of Event\",\r\n  \"placeSchema\" : \"Seralized place schema\",\r\n  \"status\" : \"done\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<EventDTO>(exampleJson)
            : default(EventDTO);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Return list of all events
        /// </summary>
        /// <response code="200">successful operation</response>
        [HttpGet]
        [Route("/events")]
        public virtual IActionResult GetEvents()
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<Event>));
            string exampleJson = null;
            exampleJson = "[ {\r\n  \"name\" : \"Long description of Event\",\r\n  \"freePlace\" : 2,\r\n  \"startTime\" : 1673034164,\r\n  \"id\" : 10,\r\n  \"endTime\" : 1683034164,\r\n  \"categories\" : [ {\r\n    \"name\" : \"Sport\",\r\n    \"id\" : 1\r\n  }, {\r\n    \"name\" : \"Sport\",\r\n    \"id\" : 1\r\n  } ],\r\n  \"title\" : \"Short description of Event\",\r\n  \"placeSchema\" : \"Seralized place schema\",\r\n  \"status\" : \"done\"\r\n}, {\r\n  \"name\" : \"Long description of Event\",\r\n  \"freePlace\" : 2,\r\n  \"startTime\" : 1673034164,\r\n  \"id\" : 10,\r\n  \"endTime\" : 1683034164,\r\n  \"categories\" : [ {\r\n    \"name\" : \"Sport\",\r\n    \"id\" : 1\r\n  }, {\r\n    \"name\" : \"Sport\",\r\n    \"id\" : 1\r\n  } ],\r\n  \"title\" : \"Short description of Event\",\r\n  \"placeSchema\" : \"Seralized place schema\",\r\n  \"status\" : \"done\"\r\n} ]";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<EventDTO>>(exampleJson)
            : default(List<EventDTO>);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Return list of events made by organizer, according to session
        /// </summary>
        /// <param name="sessionToken">session Token</param>
        /// <response code="200">successful operation</response>
        [HttpGet]
        [Route("/events/my")]
        public virtual IActionResult GetMyEvents([FromHeader][Required()]string sessionToken)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(List<Event>));
            string exampleJson = null;
            exampleJson = "[ {\r\n  \"name\" : \"Long description of Event\",\r\n  \"freePlace\" : 2,\r\n  \"startTime\" : 1673034164,\r\n  \"id\" : 10,\r\n  \"endTime\" : 1683034164,\r\n  \"categories\" : [ {\r\n    \"name\" : \"Sport\",\r\n    \"id\" : 1\r\n  }, {\r\n    \"name\" : \"Sport\",\r\n    \"id\" : 1\r\n  } ],\r\n  \"title\" : \"Short description of Event\",\r\n  \"placeSchema\" : \"Seralized place schema\",\r\n  \"status\" : \"done\"\r\n}, {\r\n  \"name\" : \"Long description of Event\",\r\n  \"freePlace\" : 2,\r\n  \"startTime\" : 1673034164,\r\n  \"id\" : 10,\r\n  \"endTime\" : 1683034164,\r\n  \"categories\" : [ {\r\n    \"name\" : \"Sport\",\r\n    \"id\" : 1\r\n  }, {\r\n    \"name\" : \"Sport\",\r\n    \"id\" : 1\r\n  } ],\r\n  \"title\" : \"Short description of Event\",\r\n  \"placeSchema\" : \"Seralized place schema\",\r\n  \"status\" : \"done\"\r\n} ]";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<List<EventDTO>>(exampleJson)
            : default(List<EventDTO>);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// patch existing event
        /// </summary>
        /// <param name="sessionToken">session Token</param>
        /// <param name="id">id of Event</param>
        /// <param name="_event">Update an existent user in the store</param>
        /// <response code="202">patched</response>
        /// <response code="404">id not found</response>
        [HttpPatch]
        [Route("/events/{id}")]
        [Consumes("application/json")]
        public virtual IActionResult PatchEvent([FromHeader][Required()]string sessionToken, [FromRoute (Name = "id")][Required]string id, [FromBody]EventDTO _event)
        {

            //TODO: Uncomment the next line to return response 202 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(202);
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            throw new NotImplementedException();
        }
    }
}
