/*
 * System rezerwacji miejsc na eventy
 *
 * Niniejsza dokumentacja stanowi opis REST API implemtowanego przez serwer centralny. Endpointy 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: XXX@pw.edu.pl
 * Generated by: https://openapi-generator.tech
 */

using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Org.OpenAPITools.Models;

namespace Org.OpenAPITools.Controllers
{
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class EventOrganizerApiController : ControllerBase
    { 
        /// <summary>
        /// Confirm orginizer account
        /// </summary>
        /// <param name="id">id of Organizer</param>
        /// <param name="code">code from email</param>
        /// <response code="201">account confirmed</response>
        /// <response code="400">code wrong</response>
        [HttpPost]
        [Route("/organizer/{id}")]
        public virtual IActionResult Confirm([FromRoute (Name = "id")][Required]string id, [FromQuery (Name = "code")][Required()]string code)
        {

            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default(Organizer));
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);
            string exampleJson = null;
            exampleJson = "{\r\n  \"password\" : \"12345\",\r\n  \"name\" : \"theUser\",\r\n  \"id\" : 10,\r\n  \"email\" : \"john@email.com\",\r\n  \"events\" : [ {\r\n    \"name\" : \"Long description of Event\",\r\n    \"freePlace\" : 2,\r\n    \"startTime\" : 1673034164,\r\n    \"id\" : 10,\r\n    \"endTime\" : 1683034164,\r\n    \"categories\" : [ {\r\n      \"name\" : \"Sport\",\r\n      \"id\" : 1\r\n    }, {\r\n      \"name\" : \"Sport\",\r\n      \"id\" : 1\r\n    } ],\r\n    \"title\" : \"Short description of Event\",\r\n    \"placeSchema\" : \"Seralized place schema\",\r\n    \"status\" : \"done\"\r\n  }, {\r\n    \"name\" : \"Long description of Event\",\r\n    \"freePlace\" : 2,\r\n    \"startTime\" : 1673034164,\r\n    \"id\" : 10,\r\n    \"endTime\" : 1683034164,\r\n    \"categories\" : [ {\r\n      \"name\" : \"Sport\",\r\n      \"id\" : 1\r\n    }, {\r\n      \"name\" : \"Sport\",\r\n      \"id\" : 1\r\n    } ],\r\n    \"title\" : \"Short description of Event\",\r\n    \"placeSchema\" : \"Seralized place schema\",\r\n    \"status\" : \"done\"\r\n  } ],\r\n  \"status\" : \"pending\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<Organizer>(exampleJson)
            : default(Organizer);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Confirm orginizer account
        /// </summary>
        /// <param name="sessionToken">session Token</param>
        /// <param name="id">id of Organizer</param>
        /// <response code="204">deleted</response>
        /// <response code="404">id not found</response>
        [HttpDelete]
        [Route("/organizer/{id}")]
        public virtual IActionResult DeleteOrganizer([FromHeader][Required()]string sessionToken, [FromRoute (Name = "id")][Required]string id)
        {

            //TODO: Uncomment the next line to return response 204 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(204);
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Logs organizer into the system
        /// </summary>
        /// <param name="email">The organizer email for login</param>
        /// <param name="password">the password</param>
        /// <response code="200">successful operation</response>
        /// <response code="400">Invalid email/password supplied</response>
        [HttpGet]
        [Route("/organizer/login")]
        public virtual IActionResult LoginOrganizer([FromQuery (Name = "email")][Required()]string email, [FromQuery (Name = "password")][Required()]string password)
        {

            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(LoginOrganizer200Response));
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);
            string exampleJson = null;
            exampleJson = "{\r\n  \"sessionToken\" : \"sessionToken\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<LoginOrganizer200Response>(exampleJson)
            : default(LoginOrganizer200Response);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// Patch orginizer account
        /// </summary>
        /// <param name="sessionToken">session Token</param>
        /// <param name="id">id of Organizer</param>
        /// <param name="organizer">Update an existent user in the store</param>
        /// <response code="202">patched</response>
        /// <response code="404">id not found</response>
        [HttpPatch]
        [Route("/organizer/{id}")]
        [Consumes("application/json")]
        public virtual IActionResult PatchOrganizer([FromHeader][Required()]string sessionToken, [FromRoute (Name = "id")][Required]string id, [FromBody]Organizer organizer)
        {

            //TODO: Uncomment the next line to return response 202 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(202);
            //TODO: Uncomment the next line to return response 404 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(404);

            throw new NotImplementedException();
        }

        /// <summary>
        /// Create orginizer account
        /// </summary>
        /// <param name="name">name of Organizer</param>
        /// <param name="email">email of Organizer</param>
        /// <param name="password">password of Organizer</param>
        /// <response code="201">successful operation</response>
        /// <response code="400">organizer already exist</response>
        [HttpPost]
        [Route("/organizer")]
        public virtual IActionResult SignUp([FromQuery (Name = "name")][Required()]string name, [FromQuery (Name = "email")][Required()]string email, [FromQuery (Name = "password")][Required()]string password)
        {

            //TODO: Uncomment the next line to return response 201 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(201, default(Organizer));
            //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(400);
            string exampleJson = null;
            exampleJson = "{\r\n  \"password\" : \"12345\",\r\n  \"name\" : \"theUser\",\r\n  \"id\" : 10,\r\n  \"email\" : \"john@email.com\",\r\n  \"events\" : [ {\r\n    \"name\" : \"Long description of Event\",\r\n    \"freePlace\" : 2,\r\n    \"startTime\" : 1673034164,\r\n    \"id\" : 10,\r\n    \"endTime\" : 1683034164,\r\n    \"categories\" : [ {\r\n      \"name\" : \"Sport\",\r\n      \"id\" : 1\r\n    }, {\r\n      \"name\" : \"Sport\",\r\n      \"id\" : 1\r\n    } ],\r\n    \"title\" : \"Short description of Event\",\r\n    \"placeSchema\" : \"Seralized place schema\",\r\n    \"status\" : \"done\"\r\n  }, {\r\n    \"name\" : \"Long description of Event\",\r\n    \"freePlace\" : 2,\r\n    \"startTime\" : 1673034164,\r\n    \"id\" : 10,\r\n    \"endTime\" : 1683034164,\r\n    \"categories\" : [ {\r\n      \"name\" : \"Sport\",\r\n      \"id\" : 1\r\n    }, {\r\n      \"name\" : \"Sport\",\r\n      \"id\" : 1\r\n    } ],\r\n    \"title\" : \"Short description of Event\",\r\n    \"placeSchema\" : \"Seralized place schema\",\r\n    \"status\" : \"done\"\r\n  } ],\r\n  \"status\" : \"pending\"\r\n}";
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<Organizer>(exampleJson)
            : default(Organizer);
            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
